# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/ftrace/power.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(protos/perfetto/trace/ftrace/power.proto\x12\x0fperfetto.protos\"8\n\x17\x43puFrequencyFtraceEvent\x12\r\n\x05state\x18\x01 \x01(\r\x12\x0e\n\x06\x63pu_id\x18\x02 \x01(\r\"S\n\x1d\x43puFrequencyLimitsFtraceEvent\x12\x10\n\x08min_freq\x18\x01 \x01(\r\x12\x10\n\x08max_freq\x18\x02 \x01(\r\x12\x0e\n\x06\x63pu_id\x18\x03 \x01(\r\"3\n\x12\x43puIdleFtraceEvent\x12\r\n\x05state\x18\x01 \x01(\r\x12\x0e\n\x06\x63pu_id\x18\x02 \x01(\r\"E\n\x16\x43lockEnableFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x04\x12\x0e\n\x06\x63pu_id\x18\x03 \x01(\x04\"F\n\x17\x43lockDisableFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x04\x12\x0e\n\x06\x63pu_id\x18\x03 \x01(\x04\"F\n\x17\x43lockSetRateFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x04\x12\x0e\n\x06\x63pu_id\x18\x03 \x01(\x04\"F\n\x18SuspendResumeFtraceEvent\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x05\x12\r\n\x05start\x18\x03 \x01(\r\"8\n\x17GpuFrequencyFtraceEvent\x12\x0e\n\x06gpu_id\x18\x01 \x01(\r\x12\r\n\x05state\x18\x02 \x01(\r\">\n\x1fWakeupSourceActivateFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x04\"@\n!WakeupSourceDeactivateFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.ftrace.power_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CPUFREQUENCYFTRACEEVENT._serialized_start=61
  _CPUFREQUENCYFTRACEEVENT._serialized_end=117
  _CPUFREQUENCYLIMITSFTRACEEVENT._serialized_start=119
  _CPUFREQUENCYLIMITSFTRACEEVENT._serialized_end=202
  _CPUIDLEFTRACEEVENT._serialized_start=204
  _CPUIDLEFTRACEEVENT._serialized_end=255
  _CLOCKENABLEFTRACEEVENT._serialized_start=257
  _CLOCKENABLEFTRACEEVENT._serialized_end=326
  _CLOCKDISABLEFTRACEEVENT._serialized_start=328
  _CLOCKDISABLEFTRACEEVENT._serialized_end=398
  _CLOCKSETRATEFTRACEEVENT._serialized_start=400
  _CLOCKSETRATEFTRACEEVENT._serialized_end=470
  _SUSPENDRESUMEFTRACEEVENT._serialized_start=472
  _SUSPENDRESUMEFTRACEEVENT._serialized_end=542
  _GPUFREQUENCYFTRACEEVENT._serialized_start=544
  _GPUFREQUENCYFTRACEEVENT._serialized_end=600
  _WAKEUPSOURCEACTIVATEFTRACEEVENT._serialized_start=602
  _WAKEUPSOURCEACTIVATEFTRACEEVENT._serialized_end=664
  _WAKEUPSOURCEDEACTIVATEFTRACEEVENT._serialized_start=666
  _WAKEUPSOURCEDEACTIVATEFTRACEEVENT._serialized_end=730
# @@protoc_insertion_point(module_scope)
