# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/ftrace/regulator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,protos/perfetto/trace/ftrace/regulator.proto\x12\x0fperfetto.protos\"+\n\x1bRegulatorDisableFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\"3\n#RegulatorDisableCompleteFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x1aRegulatorEnableFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\"RegulatorEnableCompleteFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x1fRegulatorEnableDelayFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\"H\n\x1eRegulatorSetVoltageFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03min\x18\x02 \x01(\x05\x12\x0b\n\x03max\x18\x03 \x01(\x05\"C\n&RegulatorSetVoltageCompleteFtraceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.ftrace.regulator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGULATORDISABLEFTRACEEVENT._serialized_start=65
  _REGULATORDISABLEFTRACEEVENT._serialized_end=108
  _REGULATORDISABLECOMPLETEFTRACEEVENT._serialized_start=110
  _REGULATORDISABLECOMPLETEFTRACEEVENT._serialized_end=161
  _REGULATORENABLEFTRACEEVENT._serialized_start=163
  _REGULATORENABLEFTRACEEVENT._serialized_end=205
  _REGULATORENABLECOMPLETEFTRACEEVENT._serialized_start=207
  _REGULATORENABLECOMPLETEFTRACEEVENT._serialized_end=257
  _REGULATORENABLEDELAYFTRACEEVENT._serialized_start=259
  _REGULATORENABLEDELAYFTRACEEVENT._serialized_end=306
  _REGULATORSETVOLTAGEFTRACEEVENT._serialized_start=308
  _REGULATORSETVOLTAGEFTRACEEVENT._serialized_end=380
  _REGULATORSETVOLTAGECOMPLETEFTRACEEVENT._serialized_start=382
  _REGULATORSETVOLTAGECOMPLETEFTRACEEVENT._serialized_end=449
# @@protoc_insertion_point(module_scope)
