# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/ftrace/test_bundle_wrapper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.ftrace import ftrace_event_bundle_pb2 as protos_dot_perfetto_dot_trace_dot_ftrace_dot_ftrace__event__bundle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/trace/ftrace/test_bundle_wrapper.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/trace/ftrace/ftrace_event_bundle.proto\"f\n\x11TestBundleWrapper\x12\x0e\n\x06\x62\x65\x66ore\x18\x01 \x01(\t\x12\x32\n\x06\x62undle\x18\x02 \x03(\x0b\x32\".perfetto.protos.FtraceEventBundle\x12\r\n\x05\x61\x66ter\x18\x03 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.ftrace.test_bundle_wrapper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTBUNDLEWRAPPER._serialized_start=131
  _TESTBUNDLEWRAPPER._serialized_end=233
# @@protoc_insertion_point(module_scope)
