# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/config/chrome/scenario_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.config import trace_config_pb2 as protos_dot_perfetto_dot_config_dot_trace__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protos/perfetto/config/chrome/scenario_config.proto\x12\x0fperfetto.protos\x1a)protos/perfetto/config/trace_config.proto\"\x8f\x03\n\x0bTriggerRule\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0etrigger_chance\x18\x02 \x01(\x02\x12\x10\n\x08\x64\x65lay_ms\x18\x03 \x01(\x04\x12\x1d\n\x13manual_trigger_name\x18\x04 \x01(\tH\x00\x12\x42\n\thistogram\x18\x05 \x01(\x0b\x32-.perfetto.protos.TriggerRule.HistogramTriggerH\x00\x12L\n\x12repeating_interval\x18\x06 \x01(\x0b\x32..perfetto.protos.TriggerRule.RepeatingIntervalH\x00\x1aP\n\x10HistogramTrigger\x12\x16\n\x0ehistogram_name\x18\x01 \x01(\t\x12\x11\n\tmin_value\x18\x02 \x01(\x03\x12\x11\n\tmax_value\x18\x03 \x01(\x03\x1a:\n\x11RepeatingInterval\x12\x11\n\tperiod_ms\x18\x01 \x01(\x04\x12\x12\n\nrandomized\x18\x02 \x01(\x08\x42\t\n\x07trigger\"\xc6\x01\n\x14NestedScenarioConfig\x12\x15\n\rscenario_name\x18\x01 \x01(\t\x12\x31\n\x0bstart_rules\x18\x02 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\x12\x30\n\nstop_rules\x18\x03 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\x12\x32\n\x0cupload_rules\x18\x04 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\"\xe8\x02\n\x0eScenarioConfig\x12\x15\n\rscenario_name\x18\x01 \x01(\t\x12\x31\n\x0bstart_rules\x18\x02 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\x12\x30\n\nstop_rules\x18\x03 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\x12\x32\n\x0cupload_rules\x18\x04 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\x12\x31\n\x0bsetup_rules\x18\x05 \x03(\x0b\x32\x1c.perfetto.protos.TriggerRule\x12\x32\n\x0ctrace_config\x18\x06 \x01(\x0b\x32\x1c.perfetto.protos.TraceConfig\x12?\n\x10nested_scenarios\x18\x07 \x03(\x0b\x32%.perfetto.protos.NestedScenarioConfig\"N\n\x18\x43hromeFieldTracingConfig\x12\x32\n\tscenarios\x18\x01 \x03(\x0b\x32\x1f.perfetto.protos.ScenarioConfig')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.config.chrome.scenario_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIGGERRULE._serialized_start=116
  _TRIGGERRULE._serialized_end=515
  _TRIGGERRULE_HISTOGRAMTRIGGER._serialized_start=364
  _TRIGGERRULE_HISTOGRAMTRIGGER._serialized_end=444
  _TRIGGERRULE_REPEATINGINTERVAL._serialized_start=446
  _TRIGGERRULE_REPEATINGINTERVAL._serialized_end=504
  _NESTEDSCENARIOCONFIG._serialized_start=518
  _NESTEDSCENARIOCONFIG._serialized_end=716
  _SCENARIOCONFIG._serialized_start=719
  _SCENARIOCONFIG._serialized_end=1079
  _CHROMEFIELDTRACINGCONFIG._serialized_start=1081
  _CHROMEFIELDTRACINGCONFIG._serialized_end=1159
# @@protoc_insertion_point(module_scope)
