# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/common/commit_data_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/common/commit_data_request.proto\x12\x0fperfetto.protos\"\xda\x03\n\x11\x43ommitDataRequest\x12G\n\x0e\x63hunks_to_move\x18\x01 \x03(\x0b\x32/.perfetto.protos.CommitDataRequest.ChunksToMove\x12H\n\x0f\x63hunks_to_patch\x18\x02 \x03(\x0b\x32/.perfetto.protos.CommitDataRequest.ChunkToPatch\x12\x18\n\x10\x66lush_request_id\x18\x03 \x01(\x04\x1a\x42\n\x0c\x43hunksToMove\x12\x0c\n\x04page\x18\x01 \x01(\r\x12\r\n\x05\x63hunk\x18\x02 \x01(\r\x12\x15\n\rtarget_buffer\x18\x03 \x01(\r\x1a\xd3\x01\n\x0c\x43hunkToPatch\x12\x15\n\rtarget_buffer\x18\x01 \x01(\r\x12\x11\n\twriter_id\x18\x02 \x01(\r\x12\x10\n\x08\x63hunk_id\x18\x03 \x01(\r\x12\x46\n\x07patches\x18\x04 \x03(\x0b\x32\x35.perfetto.protos.CommitDataRequest.ChunkToPatch.Patch\x12\x18\n\x10has_more_patches\x18\x05 \x01(\x08\x1a%\n\x05Patch\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.common.commit_data_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMITDATAREQUEST._serialized_start=70
  _COMMITDATAREQUEST._serialized_end=544
  _COMMITDATAREQUEST_CHUNKSTOMOVE._serialized_start=264
  _COMMITDATAREQUEST_CHUNKSTOMOVE._serialized_end=330
  _COMMITDATAREQUEST_CHUNKTOPATCH._serialized_start=333
  _COMMITDATAREQUEST_CHUNKTOPATCH._serialized_end=544
  _COMMITDATAREQUEST_CHUNKTOPATCH_PATCH._serialized_start=507
  _COMMITDATAREQUEST_CHUNKTOPATCH_PATCH._serialized_end=544
# @@protoc_insertion_point(module_scope)
