# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/common/observable_events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.protos/perfetto/common/observable_events.proto\x12\x0fperfetto.protos\"\xff\x03\n\x10ObservableEvents\x12_\n\x16instance_state_changes\x18\x01 \x03(\x0b\x32?.perfetto.protos.ObservableEvents.DataSourceInstanceStateChange\x12 \n\x18\x61ll_data_sources_started\x18\x02 \x01(\x08\x1a\x9a\x01\n\x1d\x44\x61taSourceInstanceStateChange\x12\x15\n\rproducer_name\x18\x01 \x01(\t\x12\x18\n\x10\x64\x61ta_source_name\x18\x02 \x01(\t\x12H\n\x05state\x18\x03 \x01(\x0e\x32\x39.perfetto.protos.ObservableEvents.DataSourceInstanceState\"`\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x1f\n\x1bTYPE_DATA_SOURCES_INSTANCES\x10\x01\x12!\n\x1dTYPE_ALL_DATA_SOURCES_STARTED\x10\x02\"i\n\x17\x44\x61taSourceInstanceState\x12&\n\"DATA_SOURCE_INSTANCE_STATE_STOPPED\x10\x01\x12&\n\"DATA_SOURCE_INSTANCE_STATE_STARTED\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.common.observable_events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVABLEEVENTS._serialized_start=68
  _OBSERVABLEEVENTS._serialized_end=579
  _OBSERVABLEEVENTS_DATASOURCEINSTANCESTATECHANGE._serialized_start=220
  _OBSERVABLEEVENTS_DATASOURCEINSTANCESTATECHANGE._serialized_end=374
  _OBSERVABLEEVENTS_TYPE._serialized_start=376
  _OBSERVABLEEVENTS_TYPE._serialized_end=472
  _OBSERVABLEEVENTS_DATASOURCEINSTANCESTATE._serialized_start=474
  _OBSERVABLEEVENTS_DATASOURCEINSTANCESTATE._serialized_end=579
# @@protoc_insertion_point(module_scope)
