# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/test_extensions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.track_event import track_event_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2
from protos.perfetto.trace.track_event import debug_annotation_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_debug__annotation__pb2

from protos.perfetto.trace.track_event.track_event_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+protos/perfetto/trace/test_extensions.proto\x12\x0fperfetto.protos\x1a\x33protos/perfetto/trace/track_event/track_event.proto\x1a\x38protos/perfetto/trace/track_event/debug_annotation.proto\"\xca\x02\n\rTestExtension2B\n\x1cstring_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xacM \x01(\t2?\n\x19int_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xadM \x03(\x05\x32\x43\n\x1domitted_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xaeM \x01(\t2o\n$nested_message_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xafM \x01(\x0b\x32#.perfetto.protos.TestExtensionChild\"r\n\x12TestExtensionChild\x12\x1f\n\x17\x63hild_field_for_testing\x18\x01 \x01(\t\x12;\n\x11\x64\x65\x62ug_annotations\x18\x63 \x03(\x0b\x32 .perfetto.protos.DebugAnnotationP\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.test_extensions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2.TrackEvent.RegisterExtension(_TESTEXTENSION.extensions_by_name['string_extension_for_testing'])
  protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2.TrackEvent.RegisterExtension(_TESTEXTENSION.extensions_by_name['int_extension_for_testing'])
  protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2.TrackEvent.RegisterExtension(_TESTEXTENSION.extensions_by_name['omitted_extension_for_testing'])
  protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2.TrackEvent.RegisterExtension(_TESTEXTENSION.extensions_by_name['nested_message_extension_for_testing'])

  DESCRIPTOR._options = None
  _TESTEXTENSION._serialized_start=176
  _TESTEXTENSION._serialized_end=506
  _TESTEXTENSIONCHILD._serialized_start=508
  _TESTEXTENSIONCHILD._serialized_end=622
# @@protoc_insertion_point(module_scope)
