# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/trace/statsd/statsd_atom.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.protos/perfetto/trace/statsd/statsd_atom.proto\x12\x0fperfetto.protos\"\x0c\n\nOpaqueAtom\"9\n\nStatsdAtom\x12+\n\x06nested\x18\x01 \x03(\x0b\x32\x1b.perfetto.protos.OpaqueAtom')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.statsd.statsd_atom_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPAQUEATOM._serialized_start=67
  _OPAQUEATOM._serialized_end=79
  _STATSDATOM._serialized_start=81
  _STATSDATOM._serialized_end=138
# @@protoc_insertion_point(module_scope)
