# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/perfetto/config/interceptor_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.config.interceptors import console_config_pb2 as protos_dot_perfetto_dot_config_dot_interceptors_dot_console__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/protos/perfetto/config/interceptor_config.proto\x12\x0fperfetto.protos\x1a\x38protos/perfetto/config/interceptors/console_config.proto\"]\n\x11InterceptorConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x0e\x63onsole_config\x18\x64 \x01(\x0b\x32\x1e.perfetto.protos.ConsoleConfigB\x02(\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.config.interceptor_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERCEPTORCONFIG.fields_by_name['console_config']._options = None
  _INTERCEPTORCONFIG.fields_by_name['console_config']._serialized_options = b'(\001'
  _INTERCEPTORCONFIG._serialized_start=126
  _INTERCEPTORCONFIG._serialized_end=219
# @@protoc_insertion_point(module_scope)
